### ISSUE TITLE
Corregir bug

### ISSUE THREAD

**Issue by ghost** [HuayraLinux/TierraLuna#25]
Quiero reportar un bug en la pantalla config, estaria faltando una linea que diga que si no se selecciono ningun tema quede por defecto el tema original, porque si no llego a seleccionar nadaningun tema y pongo volver se produce un error.

**Comment by malefico3d** [comment]
Gracias por el reporte, acabo de arreglarlo.  No es necesario hacer una modificación como la que propones porque ya por defecto está seleccionada la opcion "Original" que es el tema que efectivamente se carga si no se selecciona otro. El error era un problema en el boton "Volver" que ha sido corregido.

**Comment by ghost** [comment]
Buenísimo que bueno que ya este solucionado, seguiré trasteando el juego y aviso si encuentro otro bug. Un abrazo
